Repository kiwiproject/dropwizard-curator, pull requests merged in 2021-12, with the labels that each got.

#110 Add bom
  .github/dependabot.yml
  pom.xml
Labels: dependencies

#111 Replace concatenation with parameterized logging in CuratorLockHelper
  src/main/java/org/kiwiproject/curator/CuratorLockHelper.java
Labels: code cleanup

#112 Fixing a few grammatical errors that IntelliJ's code analysis flagged
  .github/workflows/build.yml
  pom.xml
  src/main/java/org/kiwiproject/curator/CuratorFrameworkHelper.java
  src/main/java/org/kiwiproject/curator/config/CuratorConfig.java
  src/main/java/org/kiwiproject/curator/health/CuratorHealthCheck.java
  src/test/java/org/kiwiproject/curator/health/CuratorHealthCheckTest.java
Labels: documentation
